// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dajzojdlckxmqcxlvzsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhanpvamRsY2t4bXFjeGx2enN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDQ3MDQsImV4cCI6MjA2MjE4MDcwNH0.qc_7108k0Y6Hys5O1hwI1ZidY8egImft6r3pRwDkEXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);