// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owfvjqftoncutmrefjrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93ZnZqcWZ0b25jdXRtcmVmanJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzkzNTksImV4cCI6MjA2MjgxNTM1OX0.myvGkjjevkMS1R7B9yHrja1roa7siflbHofIGvlUGZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);